export type HistoryStatus = "Removed" | "Issue" | "Approved" | "Pending"

export type HistoryEntry = {
  name: string
  kind: "Component" | "Style" | "Theme"
  change: "New" | "Update"
  date: string
  previewLink: string
  status: HistoryStatus
  sourceUrl: string
}

export const historyEntries: HistoryEntry[] = [
  {
    name: "Design system scaffold (monorepo)",
    kind: "Style",
    change: "New",
    date: "2026-08-24T12:34:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://ui.shadcn.com",
  },
  {
    name: "b38BAMFiE theme preset",
    kind: "Theme",
    change: "New",
    date: "2026-08-24T12:35:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://ui.shadcn.com",
  },
  {
    name: "Full shadcn component library (62 components)",
    kind: "Component",
    change: "New",
    date: "2026-08-24T12:40:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://ui.shadcn.com",
  },
  {
    name: "shadcnstudio \"maia\" theme",
    kind: "Theme",
    change: "Update",
    date: "2026-08-24T12:50:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://shadcnstudio.com",
  },
  {
    name: "Custom warm cream theme + typography",
    kind: "Theme",
    change: "Update",
    date: "2026-08-24T12:55:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Background/card color tuning (#FFFDF6 / #FFFFFF)",
    kind: "Theme",
    change: "Update",
    date: "2026-08-24T12:58:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Light grey inputs & switch",
    kind: "Theme",
    change: "Update",
    date: "2026-08-24T13:00:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Active tab matches primary button",
    kind: "Style",
    change: "Update",
    date: "2026-08-24T13:02:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Animate UI primitives, Base UI components & icons",
    kind: "Component",
    change: "New",
    date: "2026-08-24T13:15:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://animate-ui.com",
  },
  {
    name: "mcpcn MCP-app blocks",
    kind: "Component",
    change: "New",
    date: "2026-08-24T13:25:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://github.com/shadcn-labs/mcpcn",
  },
  {
    name: "Copy / Icon / Ripple / Theme Toggler buttons",
    kind: "Component",
    change: "New",
    date: "2026-08-24T13:35:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://animate-ui.com/docs/components",
  },
  {
    name: "Bubble background (brand colors)",
    kind: "Style",
    change: "New",
    date: "2026-08-24T13:36:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://animate-ui.com/docs/components",
  },
  {
    name: "Community components (management bar, notifications, todo, share)",
    kind: "Component",
    change: "New",
    date: "2026-08-24T13:37:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://animate-ui.com/docs/components",
  },
  {
    name: "Community components retheme to design tokens",
    kind: "Style",
    change: "Update",
    date: "2026-08-24T13:45:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Theme toggle moved to header",
    kind: "Style",
    change: "Update",
    date: "2026-08-24T13:46:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Fancy Components — 20 text components",
    kind: "Component",
    change: "New",
    date: "2026-08-24T13:50:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/text/letter-swap",
  },
  {
    name: "Animated gradient (SVG) background",
    kind: "Component",
    change: "New",
    date: "2026-08-24T13:51:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/background/animated-gradient-svg",
  },
  {
    name: "Terrae map components (Mapbox GL)",
    kind: "Component",
    change: "New",
    date: "2026-08-24T14:05:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://terrae.vercel.app/",
  },
  {
    name: "Glass theme",
    kind: "Theme",
    change: "New",
    date: "2026-08-24T14:10:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "https://glass-ui.crenspire.com/",
  },
  {
    name: "History page",
    kind: "Component",
    change: "New",
    date: "2026-08-24T14:15:00",
    previewLink: "/history",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Bug fixes: theme toggle, ripple, dropdown crash, tabs, focus ring, select hover, checkbox/radio animation",
    kind: "Style",
    change: "Update",
    date: "2026-08-24T14:40:00",
    previewLink: "/",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Automated Design QA",
    kind: "Component",
    change: "New",
    date: "2026-08-24T14:45:00",
    previewLink: "/qa",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Authentic Sans (weight 60) as core typeface",
    kind: "Theme",
    change: "Update",
    date: "2026-08-24T15:00:00",
    previewLink: "/tokens",
    status: "Pending",
    sourceUrl: "",
  },
  {
    name: "Typography & Tokens page",
    kind: "Component",
    change: "New",
    date: "2026-08-24T15:02:00",
    previewLink: "/tokens",
    status: "Pending",
    sourceUrl: "",
  },
]
